package com.paisetrail.app.export

import kotlinx.serialization.Serializable

/** Purpose-built export DTOs (spec 7.6 JSON export), deliberately decoupled from the Room
 * entities — export format and persistence schema are allowed to evolve independently, and
 * category/merchant ids are resolved to names here since an id is meaningless outside this
 * device's database. */
@Serializable
data class ExportedTransaction(
    val amountPaise: Long,
    val direction: String,
    val status: String,
    val payeeName: String?,
    val vpa: String?,
    val upiRef: String?,
    val occurredAt: Long,
    val categoryName: String?,
    val merchantName: String?,
    val placeName: String?,
    val locality: String?,
    val note: String?,
    val lat: Double? = null,
    val lng: Double? = null,
    val accuracyM: Double? = null,
    val locationQuality: String? = null,
)

@Serializable
data class ExportBundle(
    val exportedAt: Long,
    val transactionCount: Int,
    val transactions: List<ExportedTransaction>,
)

/** [id] is deliberately omitted — it's a local autogenerated key (see
 * [com.paisetrail.app.data.db.BankSmsPatternEntity]) that means nothing on another device, and
 * re-importing shouldn't need to match it since dedup is by (bankId, regex) instead. */
@Serializable
data class ExportedBankPattern(
    val bankId: String,
    val senderSuffix: String,
    val regex: String,
    val enabled: Boolean,
)

@Serializable
data class BankPatternExportBundle(
    val exportedAt: Long,
    val patternCount: Int,
    val patterns: List<ExportedBankPattern>,
)
