package com.paisetrail.app.data.db

import androidx.room.Entity
import androidx.room.PrimaryKey

/** One monthly spend limit per category (Insights screen budgeting). Deliberately 1:1 with
 * category rather than a separate autogenerated id — a category can have at most one budget. */
@Entity(tableName = "budgets")
data class BudgetEntity(
    @PrimaryKey val categoryId: Long,
    val monthlyLimitPaise: Long,
)
